[workspace]
members = ["crates/*"]
package.license = "MIT or Apache 2.0"
package.edition = "2021"
package.authors = ["joshua radin <jradin16@gmail.com>"]
package.repository = "https://github.com/joshradin/java_class_parser"

